In [5]:
import numpy as np
import matplotlib.pyplot as plt

import h5py
from tenpy.tools import hdf5_io

In [6]:
import h5py
from tenpy.tools import hdf5_io

In [4]:
import os

In [5]:
DATA_DIR = r"data/cluster_ising_2site_idmrg"

In [6]:
loaded_data = list()

for local_file_name in os.listdir(DATA_DIR):
    f_name = r"{}/{}".format(DATA_DIR, local_file_name)
    with h5py.File(f_name, 'r') as f:
        data = hdf5_io.load_from_hdf5(f)
        loaded_data.append(data)

In [7]:
loaded_data[0]

{'paramters': {'B': 1.175},
 'wavefunction': <tenpy.networks.mps.MPS at 0x7af030856a90>}

In [9]:
psi = next(d['wavefunction'] for d in loaded_data if d['paramters']['B'] == 0)

In [10]:
psi

In [11]:
print(psi.get_B(0))

<npc.Array shape=(2, 2, 2) labels=['vL', 'p', 'vR']
charge=ChargeInfo([], [])
 +1 | +1 | -1 
0 []|0 []|0 []
2   |2   |2   
[[[ 0.74313472 -0.31769339]
  [-0.23149703 -0.54150791]]

 [[ 0.54150791 -0.23149703]
  [ 0.31769339  0.74313472]]]
>


In [12]:
print(psi.get_B(1))

<npc.Array shape=(2, 2, 2) labels=['vL', 'p', 'vR']
charge=ChargeInfo([], [])
 +1 | +1 | -1 
0 []|0 []|0 []
2   |2   |2   
[[[-0.36772611  0.05771523]
  [-0.14391159 -0.91691653]]

 [[ 0.91691653 -0.14391159]
  [-0.05771523 -0.36772611]]]
>


# Comments
* Boundary conditions become important. Have an infinite MPS but a finite/segment MPO to operate with. But I think it's ok to calculate in a "finite" way?
    * Try mpo.expectation_value_power method?

In [2]:
from tenpy.networks.mpo import MPO
from tenpy.linalg.np_conserved import Array as npc_Array
from tenpy.networks.site import SpinHalfSite
from tenpy.linalg.charges import LegCharge

In [3]:
U = np.identity(2)

NameError: name 'np' is not defined

In [4]:
U[np.newaxis, np.newaxis, ...]

NameError: name 'U' is not defined

In [1]:
npc_U = (
    npc_Array
    .from_ndarray_trivial(
        U[np.newaxis, np.newaxis, ...],
        dtype=np.complex_,
        labels=['wL', 'wR', 'p', 'p*']
    )
)

NameError: name 'npc_Array' is not defined

In [32]:
print(npc_U)

<npc.Array shape=(1, 1, 2, 2) labels=['wL', 'wR', 'p', 'p*']
charge=ChargeInfo([], [])
 +1 | +1 | +1 | +1 
0 []|0 []|0 []|0 []
1   |1   |2   |2   
[[[[1.+0.j 0.+0.j]
   [0.+0.j 1.+0.j]]]]
>


In [33]:
X = np.array([[0,1],[1,0]])

In [34]:
npc_X = (
    npc_Array
    .from_ndarray_trivial(
        X[np.newaxis, np.newaxis, ...],
        dtype=np.complex_,
        labels=['wL', 'wR', 'p', 'p*']
    )
)

In [35]:
print(npc_X)

<npc.Array shape=(1, 1, 2, 2) labels=['wL', 'wR', 'p', 'p*']
charge=ChargeInfo([], [])
 +1 | +1 | +1 | +1 
0 []|0 []|0 []|0 []
1   |1   |2   |2   
[[[[0.+0.j 1.+0.j]
   [1.+0.j 0.+0.j]]]]
>


In [36]:
I = np.identity(2)

In [37]:
npc_I = (
    npc_Array
    .from_ndarray_trivial(
        I[np.newaxis, np.newaxis, ...],
        dtype=np.complex_,
        labels=['wL', 'wR', 'p', 'p*']
    )
)

In [38]:
site = SpinHalfSite(conserve=None)
mpo_U = MPO(
    [site,]*5,
    [npc_U, npc_X, npc_I, npc_X, npc_U]
)

In [41]:
psi.bc

'infinite'

In [39]:
mpo_U.expectation_value(psi)

ValueError: Only makes sense for infinite MPS