In [9]:
import numpy as np

In [5]:
import pymanopt
from pymanopt.manifolds import UnitaryGroup
from pymanopt.optimizers import SteepestDescent

In [2]:
manifold = UnitaryGroup(2)

In [4]:
optimizer = SteepestDescent()

In [10]:
w = np.array([1-1j,1+1j])
w /= np.linalg.norm(w)
w

array([0.5-0.5j, 0.5+0.5j])

In [11]:
v = np.array([1+0j, 0+0j])
v

array([1.+0.j, 0.+0.j])

In [14]:
type(manifold.random_point())

numpy.ndarray

In [18]:
u = manifold.random_point()

In [19]:
w.T.dot(u).dot(v)

(0.5563545671687197+0.03500438060553429j)

In [20]:
@pymanopt.function.numpy(manifold)
def cost(point):
    M = w.T.dot(point).dot(v)
    return 1 - (np.abs(M))**2

In [26]:
@pymanopt.function.numpy(manifold)
def grad(point):
    M = w.T.dot(point).dot(v)
    grad_M = np.outer(w.conj(),v)
    grad = -2*M*np.conj(grad_M)
    return grad

In [27]:
problem = pymanopt.Problem(manifold, cost, euclidean_gradient=grad)

In [32]:
dir(pymanopt.tools)

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'bisect_sequence',
 'extend_docstring',
 'functools',
 'is_sequence',
 'multi',
 'ndarraySequenceMixin',
 'printer',
 'return_as_class_instance',
 'typing',
 'unpack_singleton_sequence_return_value']

In [56]:
U_0 = np.sqrt(1/2)*np.array([[1,1],[1,1]])

In [57]:
result = optimizer.run(problem, initial_point=U_0)

Optimizing...
Iteration    Cost                       Gradient norm     
---------    -----------------------    --------------    
   1         +4.9999999999999989e-01    7.07106781e-01    
Terminated - min step_size reached after 1 iterations, 0.00 seconds.



In [58]:
result

OptimizerResult(point=array([[0.70710678, 0.70710678],
       [0.70710678, 0.70710678]]), cost=0.4999999999999999, iterations=1, stopping_criterion='Terminated - min step_size reached after 1 iterations, 0.00 seconds.', time=0.004629373550415039, cost_evaluations=1, step_size=0.0, gradient_norm=0.7071067811865477, log={'optimizer': 'SteepestDescent', 'stopping_criteria': {'max_time': 1000, 'max_iterations': 1000, 'min_gradient_norm': 1e-06, 'min_step_size': 1e-10, 'max_cost_evaluations': 5000}, 'optimizer_parameters': {'line_searcher': <pymanopt.optimizers.line_search.BackTrackingLineSearcher object at 0x7355263681d0>}, 'iterations': None})

In [59]:
result.point

array([[0.70710678, 0.70710678],
       [0.70710678, 0.70710678]])

In [60]:
result.cost

0.4999999999999999

In [54]:
result.cost_evaluations

1

In [55]:
result.stopping_criterion

'Terminated - min step_size reached after 1 iterations, 0.01 seconds.'

In [47]:
out_U = result.point

In [50]:
M = w.T.dot(out_U).dot(v)

In [51]:
M

(0.1372938609109004-0.7434203635442467j)

In [52]:
np.abs(M)

0.7559916938538952

Problem with the stopping criteria? Stopping too early.