In [1]:
import sys
sys.path.append('../')

In [2]:
import h5py
from tenpy.tools import hdf5_io
import tenpy
import tenpy.linalg.np_conserved as npc

import os

In [3]:
import numpy as np

In [4]:
from SPTOptimization.SymmetryActionWithBoundaryUnitaries import SymmetryActionWithBoundaryUnitaries
from SPTOptimization.Optimizers.OneSiteSolver import OneSiteSolver

# Load data

In [5]:
DATA_DIR = r"../data/transverse_cluster_200_site_dmrg"

In [6]:
f_name = DATA_DIR + r"/0_50.h5"

In [7]:
f_name

'../data/transverse_cluster_200_site_dmrg/0_50.h5'

In [8]:
with h5py.File(f_name, 'r') as f:
    data = hdf5_io.load_from_hdf5(f)
    test_psi = data['wavefunction']

# Test

In [9]:
np_I = np.array([[1,0],[0,1]])
np_X = np.array([[0,1],[1,0]])
np_Y = np.array([[0,-1j],[1j,0]])
np_Z = np.array([[1,0],[0,-1]])

## Test 1

In [10]:
test = SymmetryActionWithBoundaryUnitaries(
    test_psi,
    [np_X, np_I]*50,
    left_boundary_unitaries=[np_I,]*3,
    right_boundary_unitaries=[np_I,]*3
)

In [11]:
test.compute_svd_approximate_expectation()

(-7.12531953394994e-19+0j)

In [12]:
test_opt = OneSiteSolver(test)

In [13]:
test_opt.optimize()

In [14]:
test_opt.get_abs_expectation()

0.9306162804445153

In [15]:
test_opt.right_abs_expectations

[array([8.13733648e-08, 1.36514717e+00, 1.36514717e+00])]

In [16]:
test_opt.left_abs_expectations

[array([1.36514717, 1.36514717, 1.36514717])]

In [17]:
test_opt.symmetry_singular_value

0.499357640126897

In [18]:
test_opt.right_abs_expectations

[array([8.13733648e-08, 1.36514717e+00, 1.36514717e+00])]

In [19]:
test_opt.pad_right(7)
test_opt.pad_left(7)

In [20]:
len(test_opt.right_boundary_unitaries)

10

In [21]:
len(test_opt.left_boundary_unitaries)

10

In [24]:
test_opt.optimize()

In [25]:
test_opt.right_abs_expectations

[array([8.13733648e-08, 1.36514717e+00, 1.36514717e+00]),
 array([4.42483079e-05, 1.17708125e-01, 2.42454038e-02, 2.42928195e-02,
        6.62496683e-03, 6.62306355e-03, 1.35468557e-03, 1.35476727e-03,
        4.79031405e-05, 6.40603294e-05]),
 array([1.91281703e-04, 1.90966698e-04, 1.91721778e-04, 1.91736717e-04,
        1.91589681e-04, 1.91346795e-04, 1.91271958e-04, 1.91273478e-04,
        5.41067624e-05, 4.91967733e-05])]

In [26]:
test_opt.left_abs_expectations

[array([1.36514717, 1.36514717, 1.36514717]),
 array([1.36486960e+00, 3.56144669e-01, 3.51292466e-01, 1.00283376e-01,
        9.87564001e-02, 2.06930130e-02, 2.06744342e-02, 4.54096140e-03,
        4.50383581e-03, 1.06490586e-03]),
 array([0.0010778 , 0.00106462, 0.00106495, 0.00105665, 0.00105573,
        0.00105572, 0.00105581, 0.00105005, 0.00105005, 0.00104405])]

Something definitely wrong here...

In [27]:
test_opt2 = OneSiteSolver(test)

In [28]:
test_opt2.pad_right(7)
test_opt2.pad_left(7)

In [29]:
test_opt2.optimize()

In [30]:
test_opt2.get_abs_expectation()

3.043146059941001e-08

In [32]:
test_opt2.right_abs_expectations

[array([4.38367626e-05, 1.17640086e-01, 2.40635946e-02, 2.40445467e-02,
        6.54932690e-03, 6.54818715e-03, 1.34877031e-03, 1.34879113e-03,
        5.63538147e-04, 1.24656069e-04, 5.29447780e-05, 6.03191149e-05,
        5.70439666e-05, 5.74679822e-05, 5.78163943e-05, 5.78001882e-05,
        5.77946018e-05])]

In [33]:
test_opt2.left_abs_expectations

[array([1.36514717e+00, 3.53117396e-01, 3.53097106e-01, 1.00232646e-01,
        1.00228904e-01, 2.07997444e-02, 2.07998705e-02, 4.41026574e-03,
        4.41026637e-03, 1.05444512e-03, 1.05444461e-03, 1.05444473e-03,
        1.05444468e-03, 1.05444475e-03, 1.05444472e-03, 1.05444475e-03,
        1.05444473e-03])]