In [1]:
import sys
sys.path.append('../')

In [2]:
import h5py
from tenpy.tools import hdf5_io
import tenpy
import tenpy.linalg.np_conserved as npc

import os

In [3]:
import numpy as np

In [4]:
from SPTOptimization.SymmetryActionWithBoundaryUnitaries import SymmetryActionWithBoundaryUnitaries
from SPTOptimization.Optimizers.OneSiteSolver import OneSiteSolver
from SPTOptimization.utils import multiply_transfer_matrices

# Load data

In [5]:
DATA_DIR = r"../data/transverse_cluster_200_site_dmrg"

In [6]:
f_name = DATA_DIR + r"/0_50.h5"

In [7]:
f_name

'../data/transverse_cluster_200_site_dmrg/0_50.h5'

In [8]:
with h5py.File(f_name, 'r') as f:
    data = hdf5_io.load_from_hdf5(f)
    test_psi = data['wavefunction']

# Test

In [9]:
np_I = np.array([[1,0],[0,1]])
np_X = np.array([[0,1],[1,0]])
np_Y = np.array([[0,-1j],[1j,0]])
np_Z = np.array([[1,0],[0,-1]])

## Test 1

In [10]:
test = SymmetryActionWithBoundaryUnitaries(
    test_psi,
    [np_X, np_I]*50,
    left_boundary_unitaries=[np_I,]*3,
    right_boundary_unitaries=[np_I,]*3
)

In [11]:
test.compute_svd_approximate_expectation()

(-7.125364867846016e-19+0j)

In [12]:
test.num_right_unitary_sites

3

In [13]:
test_opt = OneSiteSolver(test)

In [14]:
test_opt.optimize()

In [15]:
test_opt.get_abs_expectation()

0.9306162804445218

In [16]:
test_opt.right_abs_expectations

[array([8.13733655e-08, 1.36514717e+00, 1.36514717e+00]),
 array([1.36514717, 1.36514717, 1.36514717])]

In [17]:
test_opt.left_abs_expectations

[array([1.36514717, 1.36514717, 1.36514717]),
 array([1.36514717, 1.36514717, 1.36514717])]

In [18]:
test_opt.symmetry_singular_value

0.499357640126897

In [19]:
test_opt.right_abs_expectations

[array([8.13733655e-08, 1.36514717e+00, 1.36514717e+00]),
 array([1.36514717, 1.36514717, 1.36514717])]

In [20]:
test_opt.pad_right(7)
test_opt.pad_left(7)

In [21]:
len(test_opt.right_boundary_unitaries)

10

In [22]:
len(test_opt.left_boundary_unitaries)

10

In [23]:
test_opt.optimize()

In [24]:
test_opt.right_abs_expectations

[array([8.13733655e-08, 1.36514717e+00, 1.36514717e+00]),
 array([1.36514717, 1.36514717, 1.36514717]),
 array([1.36514717, 1.36514717, 1.36514717, 1.36514717, 1.36514717,
        1.36514717, 1.36514717, 1.36514717, 1.36514717, 1.36514717])]

In [25]:
test_opt.left_abs_expectations

[array([1.36514717, 1.36514717, 1.36514717]),
 array([1.36514717, 1.36514717, 1.36514717]),
 array([1.36514717, 1.36514717, 1.36514717, 1.36514717, 1.36514717,
        1.36514717, 1.36514717, 1.36514717, 1.36514717, 1.36514717])]

In [26]:
test_opt2 = OneSiteSolver(test)

In [27]:
test_opt2.pad_right(7)
test_opt2.pad_left(7)

In [28]:
test_opt2.optimize()

In [29]:
test_opt2.get_abs_expectation()

0.9306162804445235

In [30]:
test_opt2.right_abs_expectations

[array([8.13733657e-08, 1.36514717e+00, 1.36514717e+00, 1.36514717e+00,
        1.36514717e+00, 1.36514717e+00, 1.36514717e+00, 1.36514717e+00,
        1.36514717e+00, 1.36514717e+00]),
 array([1.36514717, 1.36514717, 1.36514717, 1.36514717, 1.36514717,
        1.36514717, 1.36514717, 1.36514717, 1.36514717, 1.36514717])]

In [31]:
test_opt2.left_abs_expectations

[array([1.36514717, 1.36514717, 1.36514717, 1.36514717, 1.36514717,
        1.36514717, 1.36514717, 1.36514717, 1.36514717, 1.36514717]),
 array([1.36514717, 1.36514717, 1.36514717, 1.36514717, 1.36514717,
        1.36514717, 1.36514717, 1.36514717, 1.36514717, 1.36514717])]

In [32]:
lre = test_opt2.left_right_environments
rre = test_opt2.right_right_environments

In [33]:
exps_from_envs = np.array([
    multiply_transfer_matrices(le, re) for le, re in zip(lre, rre)
])

In [34]:
exps_from_envs

array([1.36514717+0.j, 1.36514717+0.j, 1.36514717+0.j, 1.36514717+0.j,
       1.36514717+0.j, 1.36514717+0.j, 1.36514717+0.j, 1.36514717+0.j,
       1.36514717+0.j, 1.36514717+0.j, 1.36514717+0.j])

In [35]:
exps_from_envs[1:] - test_opt2.right_abs_expectations[0]

array([1.36514709e+00+0.j, 8.65973959e-15+0.j, 9.10382880e-15+0.j,
       8.88178420e-15+0.j, 9.76996262e-15+0.j, 9.99200722e-15+0.j,
       1.02140518e-14+0.j, 1.06581410e-14+0.j, 1.15463195e-14+0.j,
       1.06581410e-14+0.j])

So these values agree...

In [36]:
test_opt2.rightmost_boundary_index

159

In [37]:
bool(test_opt2.right_abs_expectations)

True

In [38]:
test_opt2.optimize()

In [39]:
test_opt2.get_abs_expectation()

0.930616280444523

In [40]:
test_opt2.right_abs_expectations

[array([8.13733657e-08, 1.36514717e+00, 1.36514717e+00, 1.36514717e+00,
        1.36514717e+00, 1.36514717e+00, 1.36514717e+00, 1.36514717e+00,
        1.36514717e+00, 1.36514717e+00]),
 array([1.36514717, 1.36514717, 1.36514717, 1.36514717, 1.36514717,
        1.36514717, 1.36514717, 1.36514717, 1.36514717, 1.36514717]),
 array([1.36514717, 1.36514717, 1.36514717, 1.36514717, 1.36514717,
        1.36514717, 1.36514717, 1.36514717, 1.36514717, 1.36514717])]

In [41]:
test_opt2.left_abs_expectations

[array([1.36514717, 1.36514717, 1.36514717, 1.36514717, 1.36514717,
        1.36514717, 1.36514717, 1.36514717, 1.36514717, 1.36514717]),
 array([1.36514717, 1.36514717, 1.36514717, 1.36514717, 1.36514717,
        1.36514717, 1.36514717, 1.36514717, 1.36514717, 1.36514717]),
 array([1.36514717, 1.36514717, 1.36514717, 1.36514717, 1.36514717,
        1.36514717, 1.36514717, 1.36514717, 1.36514717, 1.36514717])]

## Test random

In [42]:
test_opt4 = OneSiteSolver(test, 10, 10, True)

In [43]:
test_opt.get_abs_expectation()

0.9306162804445224

In [44]:
random_seed_expectations = list()

In [45]:
for _ in range(100):
    rand_opt = OneSiteSolver(test, 10, 10, True)
    rand_opt.optimize()
    random_seed_expectations.append(rand_opt.get_abs_expectation())

In [46]:
import pandas as pd

In [47]:
pd_random_seed_expectations = pd.Series(random_seed_expectations)

In [48]:
pd_random_seed_expectations.describe()

count    100.000000
mean       0.728244
std        0.052079
min        0.621104
25%        0.706429
50%        0.711402
75%        0.756456
max        0.930611
dtype: float64

In [51]:
random_seed_expectations_20 = list()

In [52]:
for _ in range(100):
    rand_opt = OneSiteSolver(test, 20, 20, True)
    rand_opt.optimize()
    random_seed_expectations_20.append(rand_opt.get_abs_expectation())

In [53]:
pd_random_seed_expectations_20 = pd.Series(random_seed_expectations_20)

In [54]:
pd_random_seed_expectations_20.describe()

count    100.000000
mean       0.525418
std        0.058506
min        0.414569
25%        0.475662
50%        0.510212
75%        0.572145
max        0.708702
dtype: float64