In [1]:
import sys
sys.path.append('../')

In [2]:
import h5py
from tenpy.tools import hdf5_io
import tenpy
import tenpy.linalg.np_conserved as npc

import os

In [3]:
import numpy as np

In [4]:
from SPTOptimization.SymmetryActionWithBoundaryUnitaries import SymmetryActionWithBoundaryUnitaries
from SPTOptimization.TransferMatrixSearch import (
    TransferMatrixSearch,
    s3_to_unitary
)

# Load data

In [5]:
DATA_DIR = r"../data/transverse_cluster_200_site_dmrg"

In [6]:
loaded_data = list()

for local_file_name in os.listdir(DATA_DIR):
    f_name = r"{}/{}".format(DATA_DIR, local_file_name, ignore_unknown=False)
    with h5py.File(f_name, 'r') as f:
        data = hdf5_io.load_from_hdf5(f)
        loaded_data.append(data)

In [7]:
b_parameters = sorted(list(d['paramters']['B'] for d in loaded_data))

In [8]:
psi_dict = dict()

In [9]:
for b in b_parameters:
    psi = next(
        d['wavefunction']
        for d in loaded_data
        if d['paramters']['B'] == b
    )

    rounded_b = round(b, 1)
    psi_dict[rounded_b] = psi

In [10]:
list(psi_dict)

[0.0,
 0.1,
 0.2,
 0.3,
 0.4,
 0.5,
 0.6,
 0.7,
 0.8,
 0.9,
 1.0,
 1.1,
 1.2,
 1.3,
 1.4,
 1.5,
 1.6,
 1.7,
 1.8,
 1.9,
 2.0]

In [11]:
test_psi = psi_dict[0.5]

# Test

In [12]:
np_I = np.array([[1,0],[0,1]])
np_X = np.array([[0,1],[1,0]])
np_Y = np.array([[0,-1j],[1j,0]])
np_Z = np.array([[1,0],[0,-1]])

## Test 1

In [13]:
test = SymmetryActionWithBoundaryUnitaries(test_psi, [np_X, np_I]*50)

In [14]:
test.compute_expectation()

array(-4.39591975e-19)

In [15]:
test.expectation

array(-4.39591975e-19)

In [16]:
type(test.expectation)

numpy.ndarray

In [17]:
test.compute_svd_approximate_expectation()

<npc.Array shape=(64, 64) labels=['(vL.vL*)', '(vR.vR*)']
charge=ChargeInfo([], [])
LegPipe(shape (8, 8)->64,   |LegPipe(shape (8, 8)->64,   
    qconj (+1, -1)->+1;     |    qconj (-1, +1)->-1;     
    block numbers (1, 1)->1)|    block numbers (1, 1)->1)
 +1  |  -1                  | -1  |  +1                  
0 [] | 0 []                 |0 [] | 0 []                 
8    | 8                    |8    | 8                    
)                           |)                           
>


(-7.125247019401047e-19+0j)

In [18]:
test.np_symmetry_transfer_matrix

array([[-2.15213611e-04+0.j,  8.48334367e-08+0.j,  1.65162558e-20+0.j,
        ...,  2.22145011e-23+0.j,  1.03818938e-14+0.j,
        -2.22435456e-11+0.j],
       [-2.49678663e-01+0.j,  9.84189569e-05+0.j,  1.91834623e-17+0.j,
        ...,  2.57736601e-20+0.j,  1.20444862e-11+0.j,
        -2.58057040e-08+0.j],
       [ 2.05687038e-11+0.j, -8.10782661e-15+0.j, -1.60795230e-25+0.j,
        ...,  5.28002642e-29+0.j, -9.92232855e-22+0.j,
         2.12589204e-18+0.j],
       ...,
       [ 9.83506938e-15+0.j, -3.87681033e-18+0.j,  6.76417135e-29+0.j,
        ..., -2.51220866e-32+0.j, -4.74443440e-25+0.j,
         1.01651012e-21+0.j],
       [ 2.58057021e-08+0.j, -1.01721559e-11+0.j, -1.98130935e-24+0.j,
        ..., -2.66372968e-27+0.j, -1.24486578e-18+0.j,
         2.66716547e-15+0.j],
       [-2.66991015e-11+0.j,  1.05243183e-14+0.j,  2.05016886e-27+0.j,
        ...,  2.75504073e-30+0.j,  1.28796332e-21+0.j,
        -2.75950336e-18+0.j]])

In [19]:
test.npc_symmetry_transfer_matrix

<npc.Array shape=(8, 8, 8, 8) labels=['vL*', 'vL', 'vR', 'vR*']>

In [20]:
test.npc_symmetry_transfer_matrix.combine_legs([['vL', 'vL*'], ['vR', 'vR*']])

<npc.Array shape=(64, 64) labels=['(vL.vL*)', '(vR.vR*)']>

In [21]:
test.left_expectation

(-3.50701245068312e-11+0j)

In [22]:
test.right_expectation

(4.068655495612192e-08+0j)

In [23]:
test.symmetry_transfer_matrix_singular_vals

array([4.99357640e-01, 5.64338811e-17, 3.52817003e-17, 3.52817003e-17,
       3.52817003e-17, 3.52817003e-17, 3.52817003e-17, 3.52817003e-17,
       3.52817003e-17, 3.52817003e-17, 3.52817003e-17, 3.52817003e-17,
       3.52817003e-17, 3.52817003e-17, 3.52817003e-17, 3.52817003e-17,
       3.52817003e-17, 3.52817003e-17, 3.52817003e-17, 3.52817003e-17,
       3.52817003e-17, 3.52817003e-17, 3.52817003e-17, 3.52817003e-17,
       3.52817003e-17, 3.52817003e-17, 3.52817003e-17, 3.52817003e-17,
       3.52817003e-17, 3.52817003e-17, 3.52817003e-17, 3.52817003e-17,
       3.52817003e-17, 3.52817003e-17, 3.52817003e-17, 3.52817003e-17,
       3.52817003e-17, 3.52817003e-17, 3.52817003e-17, 3.52817003e-17,
       3.52817003e-17, 3.52817003e-17, 3.52817003e-17, 3.52817003e-17,
       3.52817003e-17, 3.52817003e-17, 3.52817003e-17, 3.52817003e-17,
       3.52817003e-17, 3.52817003e-17, 3.52817003e-17, 3.52817003e-17,
       3.52817003e-17, 3.52817003e-17, 3.52817003e-17, 3.52817003e-17,
      

In [24]:
test.svd_approximate_expectation

(-7.125247019401047e-19+0j)

## Test 2

In [25]:
test2 = SymmetryActionWithBoundaryUnitaries(
    test_psi,
    [np_X, np_I]*50,
    left_boundary_unitaries = [np_Z,],
    right_boundary_unitaries = [np_X, np_Z]
)

In [26]:
test2.compute_expectation()

array(0.93061628)

In [27]:
test2.expectation

array(0.93061628)

In [28]:
type(test2.expectation)

numpy.ndarray

In [29]:
test2.compute_svd_symmetry_action()

<npc.Array shape=(64, 64) labels=['(vL.vL*)', '(vR.vR*)']
charge=ChargeInfo([], [])
LegPipe(shape (8, 8)->64,   |LegPipe(shape (8, 8)->64,   
    qconj (+1, -1)->+1;     |    qconj (-1, +1)->-1;     
    block numbers (1, 1)->1)|    block numbers (1, 1)->1)
 +1  |  -1                  | -1  |  +1                  
0 [] | 0 []                 |0 [] | 0 []                 
8    | 8                    |8    | 8                    
)                           |)                           
>


In [30]:
type(test2.right_projected_symmetry_state)

tenpy.linalg.np_conserved.Array

In [31]:
type(test2.left_projected_symmetry_state)

tenpy.linalg.np_conserved.Array

In [32]:
type(test2.symmetry_transfer_matrix_singular_vals)

numpy.ndarray

In [33]:
test2.compute_right_boundary_expectation()

(1.3651471712007197+0j)

In [34]:
test2.compute_left_boundary_expectation()

(1.3651471712007195+0j)

In [35]:
test2.left_expectation

(1.3651471712007195+0j)

In [36]:
test2.right_expectation

(1.3651471712007197+0j)

In [37]:
test2.symmetry_transfer_matrix_singular_vals

array([4.99357640e-01, 5.64338811e-17, 3.52817003e-17, 3.52817003e-17,
       3.52817003e-17, 3.52817003e-17, 3.52817003e-17, 3.52817003e-17,
       3.52817003e-17, 3.52817003e-17, 3.52817003e-17, 3.52817003e-17,
       3.52817003e-17, 3.52817003e-17, 3.52817003e-17, 3.52817003e-17,
       3.52817003e-17, 3.52817003e-17, 3.52817003e-17, 3.52817003e-17,
       3.52817003e-17, 3.52817003e-17, 3.52817003e-17, 3.52817003e-17,
       3.52817003e-17, 3.52817003e-17, 3.52817003e-17, 3.52817003e-17,
       3.52817003e-17, 3.52817003e-17, 3.52817003e-17, 3.52817003e-17,
       3.52817003e-17, 3.52817003e-17, 3.52817003e-17, 3.52817003e-17,
       3.52817003e-17, 3.52817003e-17, 3.52817003e-17, 3.52817003e-17,
       3.52817003e-17, 3.52817003e-17, 3.52817003e-17, 3.52817003e-17,
       3.52817003e-17, 3.52817003e-17, 3.52817003e-17, 3.52817003e-17,
       3.52817003e-17, 3.52817003e-17, 3.52817003e-17, 3.52817003e-17,
       3.52817003e-17, 3.52817003e-17, 3.52817003e-17, 3.52817003e-17,
      

In [39]:
test2.compute_svd_approximate_expectation()

<npc.Array shape=(64, 64) labels=['(vL.vL*)', '(vR.vR*)']
charge=ChargeInfo([], [])
LegPipe(shape (8, 8)->64,   |LegPipe(shape (8, 8)->64,   
    qconj (+1, -1)->+1;     |    qconj (-1, +1)->-1;     
    block numbers (1, 1)->1)|    block numbers (1, 1)->1)
 +1  |  -1                  | -1  |  +1                  
0 [] | 0 []                 |0 [] | 0 []                 
8    | 8                    |8    | 8                    
)                           |)                           
>


(0.9306162804445224+0j)

In [40]:
test2.svd_approximate_expectation

(0.9306162804445224+0j)

In [41]:
test2.np_symmetry_transfer_matrix.shape

(64, 64)

Crack out the old tests

In [42]:
test_search = TransferMatrixSearch(test_psi, [np_X, np_I]*50)

In [43]:
test_search.search_step_right()

In [44]:
test_search.search_step_right()

In [45]:
test_search.search_step_left()

In [46]:
test_search.search_step_left()

In [47]:
test_search.max_overlap

0.9226475110645209

In [48]:
test_search.current_right_depth

2

In [49]:
test_search.current_left_depth

2

In [50]:
r_unitaries = test_search.right_max_s3_points

In [51]:
r_unitaries

array([[ 0.02476986, -0.99731462, -0.06574199,  0.02068793],
       [ 0.0558371 ,  0.05130515,  0.01280051, -0.99703869]])

In [ ]:
l_unitaries = test_search.left_max_s3_points

In [ ]:
l_unitaries

In [ ]:
test_search.left_max_overlap

In [ ]:
test_search.right_max_overlap

In [ ]:
test_search.max_overlap

In [ ]:
r_unitary_1 = s3_to_unitary(r_unitaries[0])
r_unitary_2 = s3_to_unitary(r_unitaries[1])

In [ ]:
l_unitary = s3_to_unitary(l_unitaries[0])

In [ ]:
test3 = SymmetryActionWithBoundaryUnitaries(
    test_psi,
    [np_X, np_I]*50,
    left_boundary_unitaries = [l_unitary,],
    right_boundary_unitaries = [r_unitary_1, r_unitary_2]
)

In [ ]:
test3.compute_expectation()

In [ ]:
np.abs(test3.expectation)

In [ ]:
test3.compute_svd_approximate_exepctation()

In [ ]:
np.abs(test3.svd_approximate_expectation)

In [ ]:
np.abs(test3.right_expectation)

In [ ]:
1.357477472779108/0.6705320732652

In [ ]:
np.abs(test3.left_expectation)

Inconsistent types... scalars vs arrays.

In [ ]:
0.45574587*2

In [ ]:
test3.symmetry_transfer_matrix_singular_vals

In [ ]:
test_search.symmetry_transfer_matrix_op_norm

Using a different gauge in each method, so can't compare scores directly.
But the right scores should still agree?

In [ ]:
np.linalg.norm(test_search.right_projected_symmetry_state - test3.right_projected_symmetry_state)

Right projected states agree...

In [ ]:
test3.right_edge_transfer_vector